baseURL: https://codefor.de
languageCode: en-us
title: Code for Germany
theme: hugo-cfg
#Disables warnings
disableKinds:
 -taxonomy
 -taxonomyTerm
pluralizeListTitles: false
frontmatter:
  date: [":filename", ":default"]

params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/cfg.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Code for Germany
    # Hero subtitle (optional)
    subtitle: Wir sind ein Netzwerk offener Stadtlabore und bauen digitale Werkzeuge für alle!
    # Button text
    buttontext: Werde Stadtentwickler*in!
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    #clientlogos:
    #- systek
    #- tribe
    #- kromo
    #- infinite
    #- gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Über uns
    url: /ueber/
  - title: Projekte
    url: /projekte/
  - title: Unterstützen
    sublinks:
    - title: als Entwickler*in / Designer*in
      url: /mitmachen/entwickeln/
    - title: als Vernetzer*in / Aktivist*in
      url: /mitmachen/vernetzen/
    - title: aus Politik / Verwaltung
      url: /mitmachen/politik/
    - title: als Journalist*in / Blogger*in
      url: /mitmachen/schreiben/
    - title: als Unterstützer*in / Sponsor*in
      url: /mitmachen/unterstuetzen/
    - title: als Bürger*in
      url: /mitmachen/gesellschaft/
  - title: Grundsätze
    url: /grundsaetze/
  - title: Blog
    url: /blog/
    button: true
  section1:
    title: 28 Labs | 300 Ehrenamtliche | 5 Jahre
    subtitle:
    tiles:
    - # title: Design & Entwicklung
      icon: mouse-globe
      text:
      url: /
      buttonText: Entwicklung & Design
    - # title: Cloud integration
      icon: laptop-cloud
      text:
      url: /
      buttonText: Politik & Verwaltung
    - # title: Add-ons & plugins
      icon: plug-cloud
      text:
      url: /
      buttonText: Journalismus & Unterstützung
  section2:
    subtitle: Freie Software + Offene Daten = <3
    title: open source + open data = <3
    features:
    - title: Offene Daten // Open Data
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Offene Verwaltung // Open Government
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Zivilgesellschaftliche Technik // Civic Tech
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: Wir nehmen offene Daten
    subtitle: und bauen daraus Anwendungen für Bürger*innen.
    image: illustrations/mockups/app-mockup.png
    buttonText: Zu den Projekten
    buttonLink: "/projekte/"
  section4:
    title: Unsere Schwerpunkte
    subtitle: für 2020
    clients:
    - name: Umwelt
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job:
      img: 1
    - name: Mobilität & Infrastruktur
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job:
      img: 2
    - name: Open Government
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job:
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: cfg.svg
    # Social Media Title
    socialmediatitle: Folge uns!
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/okfde/codefor.de
      # Icons are from Font Awesome
      icon: github
    - link: https://twitter.com/lucperkins
      icon: twitter
    bulmalogo: true
    quicklinks:
      column1:
        title: "Rechtliches"
        links:
        - text: Impressum
          link: /impressum/
        - text: Datenschutz
          link: /impressum/#datenschutzerklaerung
        - text: Code of Conduct
          link: /
        - text: OKF e.V.
          link: https://okfn.de/
      column2:
        title: "Werkzeugkoffer"
        links:
        - text: Github (extern)
          link: https://github.com/okfde
        - text: opendatahandbook.org
          link: https://opendatahandbook.org/
        - text: Grundsätze
          link: /grundsaetze
        - text: Developers
          link: /
      column3:
        title: "Über uns"
        links:
        - text: Blog
          link: /blog/
        - text: Projekte
          link: /projekte/
        - text: Die Labs 
          link: /labs/
        - text: Unterstützen
          link: /mitmachen/unterstuetzen/
