[build]
publish = "public"
command = "hugo --gc --minify -b $URL"

[context.production.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.69.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.69.2"

[[redirects]]
from = "/berlin"
to = "/labs/berlin"

[[redirects]]
from = "/bielefeld"
to = "/labs/bielefeld"

[[redirects]]
from = "/bonn"
to = "/labs/bonn"

[[redirects]]
from = "/chemnitz"
to = "/labs/chemnitz"

[[redirects]]
from = "/dresden"
to = "/labs/dresden"

[[redirects]]
from = "/duesseldorf"
to = "/labs/duesseldorf"

[[redirects]]
from = "/erlangen"
to = "/labs/erlangen"

[[redirects]]
from = "/frankfurt"
to = "/labs/frankfurt"

[[redirects]]
from = "/freiburg"
to = "/labs/freiburg"

[[redirects]]
from = "/giessen"
to = "/labs/giessen"

[[redirects]]
from = "/hamburg"
to = "/labs/hamburg"

[[redirects]]
from = "/hannover"
to = "/labs/hannover"

[[redirects]]
from = "/heidelberg"
to = "/labs/heidelberg"

[[redirects]]
from = "/heilbronn"
to = "/labs/heilbronn"

[[redirects]]
from = "/jena"
to = "/labs/jena"

[[redirects]]
from = "/karlsruhe"
to = "/labs/karlsruhe"

[[redirects]]
from = "/koeln"
to = "/labs/koeln"

[[redirects]]
from = "/leipzig"
to = "/labs/leipzig"

[[redirects]]
from = "/magdeburg"
to = "/labs/magdeburg"

[[redirects]]
from = "/mecklenburg-vorpommern"
to = "/labs/mecklenburg-vorpommern"

[[redirects]]
from = "/muenchen"
to = "/labs/muenchen"

[[redirects]]
from = "/muenster"
to = "/labs/muenster"

[[redirects]]
from = "/niederrhein"
to = "/labs/niederrhein"

[[redirects]]
from = "/osnabrueck"
to = "/labs/osnabrueck"

[[redirects]]
from = "/paderborn"
to = "/labs/paderborn"

[[redirects]]
from = "/potsdam"
to = "/labs/potsdam"

[[redirects]]
from = "/ruhrgebiet"
to = "/labs/ruhrgebiet"

[[redirects]]
from = "/saarland"
to = "/labs/saarland"

[[redirects]]
from = "/schleswig_flensburg"
to = "/labs/schleswig_flensburg"

[[redirects]]
from = "/stuttgart"
to = "/labs/stuttgart"

[[redirects]]
from = "/ulm"
to = "/labs/ulm"

[[redirects]]
from = "/wuppertal"
to = "/labs/wuppertal"

[[redirects]]
from = "/stadtgeschichten"
to = "/blog/stadtgeschichten"

[[redirects]]
from = "/en/stadtgeschichten"
to = "/blog/stadtgeschichten"

[[redirects]]
from = "/stadtgeschichten/1feinstaub"
to = "/blog/stadtgeschichte-feinstaub-stuttgart"

[[redirects]]
from = "/stadtgeschichten/2tal-o-mat"
to = "/blog/stadtgeschichte-tal-o-mat-wuppertal"

[[redirects]]
from = "/stadtgeschichten/3magdego"
to = "/blog/stadtgeschichte-magdego-magdeburg"

[[redirects]]
from = "/stadtgeschichten/4parkenDD"
to = "/blog/stadtgeschichte-parkendd-dresden"

[[redirects]]
from = "/stadtgeschichten/5muenchen-transparent"
to = "/blog/stadtgeschichte-muenchen-transparent-muenchen"

[[redirects]]
from = "/stadtgeschichten/6buerger-baut-stadt/"
to = "/blog/stadtgeschichte-buerger-baut-stadt-berlin"

[[redirects]]
from = "/en/stadtgeschichten/1feinstaub"
to = "/blog/story-air-pollution-stuttgart"

[[redirects]]
from = "/en/stadtgeschichten/2tal-o-mat"
to = "/blog/story-tal-o-mat-wuppertal"

[[redirects]]
from = "/en/stadtgeschichten/3magdego"
to = "/blog/story-magdego-magdeburg"

[[redirects]]
from = "/en/stadtgeschichten/4parkenDD"
to = "/blog/story-parkendd-dresden"

[[redirects]]
from = "/en/stadtgeschichten/5muenchen-transparent"
to = "/blog/story-muenchen-transparent-munich"

[[redirects]]
from = "/en/stadtgeschichten/6buerger-baut-stadt/"
to = "/blog/story-citizen-builds-city-berlin"
